frontend:
  image:
    repository: docker.io/hellochemo/excalidraw-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  env:
    VITE_ENABLE_REMOTE_SYNC: "true"
    VITE_REMOTE_SYNC_ENDPOINT: "http://localhost:5000"
backend:
  image:
    repository: docker.io/hellochemo/excalidraw-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5001
  env:
    MONGODB_URI: "" # Pass this in via --set or secrets.yaml
    PORT: "5001"
    NODE_ENV: "development"
