imagePullSecrets:
  - name: regcred

dockerhub:
  server: "https://index.docker.io/v1/"
  username: ""
  password: ""
  email: ""

frontend:
  image:
    repository: hellochemo/excalidraw-frontend
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 80
    nodePort: 30000
  env:
    VITE_ENABLE_REMOTE_SYNC: "true"
    VITE_REMOTE_SYNC_ENDPOINT: "http://localhost:5000"
backend:
  image:
    repository: hellochemo/excalidraw-backend
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 5001
    nodePort: 30001
  env:
    MONGODB_URI: "" # Pass this in via --set or secrets.yaml
    PORT: "5001"
    NODE_ENV: "development"
