apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "excalidraw.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "excalidraw.name" . }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "excalidraw.name" . }}-frontend
        {{- include "excalidraw.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            {{- range $key, $val := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
